/*
  scout v0.0.6
  copyright 2014 - kevin von flotow
  MIT license
*/
;(function(e){function p(){if(m)return m;for(var a in k){var b=k[a];if(b.regex&&b.regex.test(this.selector))return b.fn}return k.qsa.fn}function n(a,b){this.selector=a;this.queryFn=p.call(this);this.fn=b}function h(a){this.creator=a;this.data={}}function f(){this.length=0;this.cache=new h(this)}if(!e)return console.log("scout: fatal! window object was not found");var g=e.document;g.querySelectorAll||console.log("scout: window.querySelectorAll was not found, could cause issues depending on usage");
var m=e.jQuery||e.jqMobi||e.Zepto||e.af,k={id:{regex:/^#[-A-Za-z0-9_][-A-Za-z0-9_:.]*$/,fn:function(a){return(a=g.getElementById(a.substr(1)))?[a]:[]}},cls:{regex:/^\.[-A-Za-z0-9_:.]*$/,fn:function(a){return g.getElementsByClassName(a.substr(1))}},tag:{regex:/^[A-Za-z][-A-Za-z0-9_:.]*$/,fn:g.getElementsByTagName.bind(g)},qsa:{regex:null,fn:g.querySelectorAll.bind(g)}};n.prototype.check=function(){if(this.queryFn)for(var a=this.queryFn(this.selector),b=0,c=a.length;b<c;++b)this.fn(a[b],b)};h.prototype.update=
function(){this.data={};var a=this;a.creator.each(function(b,c){a.data[b.selector]=c});return this};h.prototype.add=function(a,b){this.data[a]=b};h.prototype.has=function(a){return"undefined"!==typeof a&&this.data.hasOwnProperty(a)};h.prototype.get=function(a){return this.has(a)?this.data[a]:-1};f.prototype.each=function(a){for(var b=0,c=this.length;b<c;++b)a(this[b],b);return this};f.prototype.on=function(a,b){var c=new n(a,b),d=this.cache.get(a),d=-1<d?d:this.length++;this[d]=c;this.cache.add(a,
d);c.check();return this};f.prototype.once=function(a,b){var c=this;c.on(a,function(d,e){c.off(a);b(d,e)});return this};f.prototype.off=function(a){a=this.cache.get(a);-1<a&&(Array.prototype.splice.apply(this,[a,1]),this.cache.update());return this};f.prototype.get=function(a,b){var c=!1,d=this.cache.get(a);-1<d&&(c=this[d]);b&&b(c);return c};f.prototype.check=function(a){"undefined"===typeof a?this.each(function(a){a.check()}):this.get(a,function(a){a&&a.check()});return this};var l=new f;"undefined"!==
typeof module?module.exports=l:"undefined"!==typeof requirejs?define(function(){return l}):e.scout=l})(window);
