/*
  scout v0.0.2
  copyright 2014 - kevin von flotow
  MIT license
*/
(function(f){function h(a,b){this.selector=a;this.fn=b}function k(a){this.creator=a;this.data={}}function l(){this.length=0;this.cache=new k(this)}if(!f)return console.log("scout: fatal! window object was not found");var d=f.document;if(!d.querySelectorAll)return console.log("scout: fatal! window.querySelectorAll was not found");var g={id:{regex:/^#/,fn:function(a){return(a=d.getElementById(a.replace(g.id.regex,"")))?[a]:[]}},cls:{regex:/^\./,fn:function(a){return d.getElementsByClassName(a.replace(g.cls.regex,
""))}},tag:{regex:/^[a-zA-Z]/,fn:d.getElementsByTagName.bind(d)},qsa:{regex:null,fn:d.querySelectorAll.bind(d)}},m=function(a){for(var b in g){var c=g[b];if(c.regex&&c.regex.test(a))return c.fn(a)||[]}return g.qsa.fn(a)},n=function(){if(f.getComputedStyle)return function(a){return"none"===f.getComputedStyle(a,null).display};console.log("scout: window.getComputedStyle is not available, could cause issues depending on usage");return function(){return!1}}();h.prototype={check:function(){for(var a=m(this.selector),
b=0,c=a.length;b<c;++b)n(a[b])||this.fn(a[b],b)}};k.prototype={update:function(){this.data={};var a=this;a.creator.each(function(b,c){a.data[b.selector]=c});return this},add:function(a,b){this.data[a]=b},has:function(a){return"undefined"!==typeof a&&this.data.hasOwnProperty(a)},get:function(a){return this.has(a)?this.data[a]:-1}};l.prototype={each:function(a){for(var b=0,c=this.length;b<c;++b)a(this[b],b);return this},on:function(a,b){var c=new h(a,b),e=this.cache.get(a),e=-1<e?e:this.length++;this[e]=
c;this.cache.add(a,e);c.check();return this},once:function(a,b){var c=this;c.on(a,function(e,d){c.off(a);b(e,d)});return this},off:function(a){a=this.cache.get(a);-1<a&&(Array.prototype.splice.apply(this,[a,1]),this.cache.update());return this},get:function(a,b){var c=!1,e=this.cache.get(a);-1<e&&(c=this[e]);b&&b(c);return c},check:function(a){"undefined"===typeof a?this.each(function(a,c){for(var e=m(a.selector),d=0,f=e.length;d<f;++d)n(e[d])||a.fn(e[d],d)}):this.get(a,function(a){a&&a.check()});
return this}};f.scout=new l})(this.window);
